# Generated by Django 6.0.5 on 2026-07-12 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('flower', 'Flower'), ('tree', 'Tree'), ('herb', 'Herb'), ('succulent', 'Succulent')], default='flower', help_text='The type of plant (affects visual appearance)', max_length=20)),
                ('stage', models.CharField(choices=[('seed', 'Seed'), ('sprout', 'Sprout'), ('growing', 'Growing'), ('mature', 'Mature'), ('blooming', 'Blooming')], default='seed', help_text='Current growth stage', max_length=20)),
                ('health', models.IntegerField(default=100, help_text='Plant health (0-100). Decreases when habits are missed.')),
                ('streak_count', models.IntegerField(default=0, help_text='Current streak count')),
                ('best_streak', models.IntegerField(default=0, help_text='Best streak ever achieved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_watered', models.DateTimeField(blank=True, help_text="When the plant was last 'watered' (habit completed)", null=True)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ['-created_at'],
            },
        ),
    ]
